export const members = [{
  id: 1,
  name: '1',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 2,
  name: '2',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 3,
  name: '3',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 4,
  name: '4',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 5,
  name: '5',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 6,
  name: '6',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 7,
  name: '7',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 8,
  name: '8',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 9,
  name: '9',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 10,
  name: '10',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}, {
  id: 11,
  name: '11',
  avator: '/images/fe-cr-random/suijiyonghu.png'
}];
